acme_calculator_ui:
    resource: "@AcmeCalculatorUIBundle/Resources/config/routing.yml"
    prefix:   /

acme_calculator_api:
    resource: "@AcmeCalculatorAPIBundle/Resources/config/routing.yml"
    prefix:   /

