acme_calculatorui_homepage:
    path:     /
    defaults: { _controller: acme_calculatorui.controller.default:indexAction }

acme_calculatorui_compute:
    path:     /compute
    defaults: { _controller: acme_calculatorui.controller.default:computeAction }

