parameters:
#    acme_calculator_ui.example.class: Acme\CalculatorUIBundle\Example

services:
#    acme_calculator_ui.example:
#        class: %acme_calculator_ui.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
